Fix name
mostlymaxi/franz pull request #2
Opened 2024-09-20 23:05 UTC by 0xRy4n

2024-09-20 23:13 UTC, mostlymaxi requested changes
bad.

2024-09-20 23:15 UTC, 0xRy4n commented
L+ratio

2024-09-21 21:58 UTC, mostlymaxi reviewed
youre bald D:

2024-09-21 21:58 UTC, 0xRy4n commented
YOUR UGLY

2024-09-21 21:58 UTC, closed without merging

2024-09-21 21:59 UTC, 0xRy4n commented
YOUR UGLY